name: Terraform Plan with Inkdrop

on:
  pull_request:

# Needed so the reusable workflow can push the inkdrop-ci-data branch
# and post PR comments.
permissions:
  contents: write
  pull-requests: write

concurrency:
  group: inkdrop-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Your plan.out is already committed at the repo root
      - name: Verify plan artifact exists
        run: |
          test -f plan.out || (echo "plan.out not found at repo root" && exit 1)

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.out

  visualize:
    needs: plan
    # Skip if PR comes from a fork, since GITHUB_TOKEN is read-only on forked PRs.
    if: ${{ github.event.pull_request.head.repo.fork == false }}
    # Pin to a valid ref: use a concrete v1.x tag or main.
    # Docs show @v2, but the repo currently publishes v1.x and main.
    uses: inkdrop-org/inkdrop-visualizer/.github/workflows/inkdrop-plan.yml@main
    with:
      terraform_version: 1.6.6
      plan_artifact: terraform-plan
      plan_file_name: plan.out
