name: Terraform Plan with Inkdrop

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If your plan.out already exists at the repo root (as you said),
      # you can skip terraform init/plan and just upload it.
      - name: Verify plan artifact exists
        run: |
          test -f plan.out || (echo "plan.out not found at repo root" && exit 1)

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: plan.out

  visualize:
    needs: plan
    # Docs show @v2, but the repo exposes v1.x tags; pin to main or a concrete tag like v1.1.49.
    # Ref: https://docs.inkdrop.ai/... (example uses @v2); repo tags show only v1.x.
    uses: inkdrop-org/inkdrop-visualizer/.github/workflows/inkdrop-plan.yml@main
    with:
      terraform_version: 1.6.6
      plan_artifact: terraform-plan
      plan_file_name: plan.out
      # diagram_readme: true   # uncomment if you also want it to update README
